package ArmAKerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.io.File;
import ArmAKerho.ArmAKerhoGUIController;
import ArmAKerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.09 11:20:46 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ArmAKerhoGUIControllerTest {



  // Generated by ComTest BEGIN
  /** testLuoTiedostot327 */
  @Test
  public void testLuoTiedostot327() {    // ArmAKerhoGUIController: 327
    ArmAKerhoGUIController ctrl = new ArmAKerhoGUIController(); 
    ctrl.luoTiedostotTest("testi"); 
    File nimet = new File("kerhot/testi/nimet.dat"); 
    File nimetBak = new File("kerhot/testi/nimet.bak"); 
    File pelipaivat = new File("kerhot/testi/pelipaivat.dat"); 
    File pelipaivatBak = new File("kerhot/testi/pelipaivat.bak"); 
    assertEquals("From: ArmAKerhoGUIController line: 339", true, nimet.exists()); 
    assertEquals("From: ArmAKerhoGUIController line: 340", true, nimetBak.exists()); 
    assertEquals("From: ArmAKerhoGUIController line: 341", true, pelipaivat.exists()); 
    assertEquals("From: ArmAKerhoGUIController line: 342", true, pelipaivatBak.exists()); 
    nimet.delete(); 
    nimetBak.delete(); 
    pelipaivat.delete(); 
    pelipaivatBak.delete(); 
  } // Generated by ComTest END
}