package Kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static Kanta.RegularExpression.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.30 09:43:43 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RegularExpressionTest {



  // Generated by ComTest BEGIN
  /** testRegulaariExp22 */
  @Test
  public void testRegulaariExp22() {    // RegularExpression: 22
    assertEquals("From: RegularExpression line: 23", false, regulaariExp("[k]", "Karel", false)); 
    assertEquals("From: RegularExpression line: 24", true, regulaariExp("[k]", "Karel", true)); 
    assertEquals("From: RegularExpression line: 25", true, regulaariExp("[K]", "Karel", false)); 
    assertEquals("From: RegularExpression line: 26", false, regulaariExp("[0-9]", "Karel", true)); 
    assertEquals("From: RegularExpression line: 27", true, regulaariExp("[^0-9]", "Karel", true)); 
    assertEquals("From: RegularExpression line: 28", true, regulaariExp("[0-9]", "Karel1", false)); 
  } // Generated by ComTest END
}