package Kerho.test;
// Generated by ComTest BEGIN
import java.util.ArrayList;
import static org.junit.Assert.*;
import org.junit.*;
import Kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.08 09:38:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaivaTest {



  // Generated by ComTest BEGIN
  /** testPaiva49 */
  @Test
  public void testPaiva49() {    // Paiva: 49
    Paiva p1 = new Paiva("5|Maanantai|12|00|13|00"); 
    String s = p1.toString(); 
    assertEquals("From: Paiva line: 52", "5|Maanantai|12|00|13|00", s); 
    Paiva p2 = new Paiva(s); 
    assertEquals("From: Paiva line: 54", "5|Maanantai|12|00|13|00", p2.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPaiva72 */
  @Test
  public void testPaiva72() {    // Paiva: 72
    Paiva p1 = new Paiva(5, "12","00","13","00",0); 
    assertEquals("From: Paiva line: 74", "5|Maanantai|12|00|13|00", p1.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPaiva92 */
  @Test
  public void testPaiva92() {    // Paiva: 92
    String[] s = { "Maanantai", "Tiistai", "Keskiviikko", "Torstai", "Perjantai", "Lauantai", "Sunnuntai"} ; 
    ArrayList<ArrayList<Paiva>> p = new ArrayList<ArrayList<Paiva>>(); 
    for (int i = 0; i < 4; i++) {
    p.add(new ArrayList<Paiva>()); 
    for (int a = 0; a < 7; a++) {
    p.get(i).add(new Paiva(i,a)); 
    }
    }
    for (int i = 0; i < 4; i++) {
    for (int a = 0; a < 7; a++) {
    assertEquals("From: Paiva line: 104", i+"|"+s[a]+"|00|00|00|00", p.get(i).get(a).toString()); 
    }
    }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetAlkuAika178 */
  @Test
  public void testGetAlkuAika178() {    // Paiva: 178
    Paiva p1 = new Paiva("5|Maanantai|12|00|13|00"); 
    assertEquals("From: Paiva line: 180", "12", p1.getAlkuAika(false)); 
    assertEquals("From: Paiva line: 181", "00", p1.getAlkuAika(true)); 
    Paiva p2 = new Paiva("5|Maanantai|12|45|13|30"); 
    assertEquals("From: Paiva line: 183", "12", p2.getAlkuAika(false)); 
    assertEquals("From: Paiva line: 184", "45", p2.getAlkuAika(true)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLoppuAika198 */
  @Test
  public void testGetLoppuAika198() {    // Paiva: 198
    Paiva p1 = new Paiva("5|Maanantai|12|00|13|00"); 
    assertEquals("From: Paiva line: 200", "13", p1.getLoppuAika(false)); 
    assertEquals("From: Paiva line: 201", "00", p1.getLoppuAika(true)); 
    Paiva p2 = new Paiva("5|Maanantai|12|45|13|30"); 
    assertEquals("From: Paiva line: 203", "13", p2.getLoppuAika(false)); 
    assertEquals("From: Paiva line: 204", "30", p2.getLoppuAika(true)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPeluriId217 */
  @Test
  public void testGetPeluriId217() {    // Paiva: 217
    Paiva maanantai = new Paiva(); 
    maanantai.taytaTestiTiedoilla(1, "Maanantai"); 
    assertEquals("From: Paiva line: 220", 1, maanantai.getPeluriId()); 
  } // Generated by ComTest END
}