package Kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import Kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.01 16:52:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaivatTest {



  // Generated by ComTest BEGIN
  /** testAnnaPaivat94 */
  @Test
  public void testAnnaPaivat94() {    // Paivat: 94
    Paivat paivat = new Paivat(); 
    Paiva maanantai2 = new Paiva("2|00|00|00|00|0"); paivat.lisaa(maanantai2); 
    Paiva maanantai1 = new Paiva("1|00|00|00|00|0"); paivat.lisaa(maanantai1); 
    Paiva tiistai2 = new Paiva("2|00|00|00|00|1"); paivat.lisaa(tiistai2); 
    Paiva keskiviikko1 = new Paiva("1|00|00|00|00|2"); paivat.lisaa(keskiviikko1); 
    Paiva perjantai2 = new Paiva("2|00|00|00|00|4"); paivat.lisaa(perjantai2); 
    Paiva maanantai5 = new Paiva("5|00|00|00|00|0"); paivat.lisaa(maanantai5); 
    List<Paiva> loytyneet; 
    loytyneet = paivat.annaPaivat(3); 
    assertEquals("From: Paivat line: 107", 0, loytyneet.size()); 
    loytyneet = paivat.annaPaivat(1); 
    assertEquals("From: Paivat line: 109", 2, loytyneet.size()); 
    assertEquals("From: Paivat line: 110", true, loytyneet.get(0) == maanantai1); 
    assertEquals("From: Paivat line: 111", true, loytyneet.get(1) == keskiviikko1); 
    loytyneet = paivat.annaPaivat(5); 
    assertEquals("From: Paivat line: 113", 1, loytyneet.size()); 
    assertEquals("From: Paivat line: 114", true, loytyneet.get(0) == maanantai5); 
  } // Generated by ComTest END
}