package Kerho.test;
// Generated by ComTest BEGIN
import java.util.ArrayList;
import static org.junit.Assert.*;
import org.junit.*;
import Kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.10 15:19:41 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaivaTest {



  // Generated by ComTest BEGIN
  /** testPaiva50 */
  @Test
  public void testPaiva50() {    // Paiva: 50
    Paiva p1 = new Paiva("5|Maanantai|12|00|13|00"); 
    String s = p1.toString(); 
    assertEquals("From: Paiva line: 53", "5|Maanantai|12|00|13|00", s); 
    Paiva p2 = new Paiva(s); 
    assertEquals("From: Paiva line: 55", "5|Maanantai|12|00|13|00", p2.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPaiva73 */
  @Test
  public void testPaiva73() {    // Paiva: 73
    Paiva p1 = new Paiva(5, "12","00","13","00",0); 
    assertEquals("From: Paiva line: 75", "5|Maanantai|12|00|13|00", p1.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPaiva93 */
  @Test
  public void testPaiva93() {    // Paiva: 93
    String[] s = { "Maanantai", "Tiistai", "Keskiviikko", "Torstai", "Perjantai", "Lauantai", "Sunnuntai"} ; 
    ArrayList<ArrayList<Paiva>> p = new ArrayList<ArrayList<Paiva>>(); 
    for (int i = 0; i < 4; i++) {
    p.add(new ArrayList<Paiva>()); 
    for (int a = 0; a < 7; a++) {
    p.get(i).add(new Paiva(i,a)); 
    }
    }
    for (int i = 0; i < 4; i++) {
    for (int a = 0; a < 7; a++) {
    assertEquals("From: Paiva line: 105", i+"|"+s[a]+"|00|00|00|00", p.get(i).get(a).toString()); 
    }
    }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetAlkuAika179 */
  @Test
  public void testGetAlkuAika179() {    // Paiva: 179
    Paiva p1 = new Paiva("5|Maanantai|12|00|13|00"); 
    assertEquals("From: Paiva line: 181", "12", p1.getAlkuAika(false)); 
    assertEquals("From: Paiva line: 182", "00", p1.getAlkuAika(true)); 
    Paiva p2 = new Paiva("5|Maanantai|12|45|13|30"); 
    assertEquals("From: Paiva line: 184", "12", p2.getAlkuAika(false)); 
    assertEquals("From: Paiva line: 185", "45", p2.getAlkuAika(true)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLoppuAika199 */
  @Test
  public void testGetLoppuAika199() {    // Paiva: 199
    Paiva p1 = new Paiva("5|Maanantai|12|00|13|00"); 
    assertEquals("From: Paiva line: 201", "13", p1.getLoppuAika(false)); 
    assertEquals("From: Paiva line: 202", "00", p1.getLoppuAika(true)); 
    Paiva p2 = new Paiva("5|Maanantai|12|45|13|30"); 
    assertEquals("From: Paiva line: 204", "13", p2.getLoppuAika(false)); 
    assertEquals("From: Paiva line: 205", "30", p2.getLoppuAika(true)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPeluriId218 */
  @Test
  public void testGetPeluriId218() {    // Paiva: 218
    Paiva maanantai = new Paiva(); 
    maanantai.taytaTestiTiedoilla(1, "Maanantai"); 
    assertEquals("From: Paiva line: 221", 1, maanantai.getPeluriId()); 
  } // Generated by ComTest END
}