package Kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.05 12:29:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaivaTest {



  // Generated by ComTest BEGIN
  /** testGetPeluriId101 */
  @Test
  public void testGetPeluriId101() {    // Paiva: 101
    Paiva maanantai = new Paiva(); 
    maanantai.taytaTestiTiedoilla(1, "Maanantai"); 
    assertEquals("From: Paiva line: 104", 1, maanantai.getPeluriId()); 
  } // Generated by ComTest END
}