package Kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.15 22:42:27 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeluriTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi61 */
  @Test
  public void testRekisteroi61() {    // Peluri: 61
    Peluri ben1 = new Peluri(); 
    assertEquals("From: Peluri line: 63", 0, ben1.getPeluriId()); 
    ben1.rekisteroi(); 
    Peluri ben2 = new Peluri(); 
    ben2.rekisteroi(); 
    int n1 = ben1.getPeluriId(); 
    int n2 = ben2.getPeluriId(); 
    assertEquals("From: Peluri line: 69", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPeluriId83 */
  @Test
  public void testGetPeluriId83() {    // Peluri: 83
    Peluri ben1 = new Peluri(); 
    ben1.rekisteroi(); 
    Peluri ben2 = new Peluri(); 
    ben2.rekisteroi(); 
    int n1 = ben1.getPeluriId(); 
    int n2 = ben2.getPeluriId(); 
    assertEquals("From: Peluri line: 90", n2-1, n1);
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPNimi111 */
  @Test
  public void testGetPNimi111() {    // Peluri: 111
    Peluri ben1 = new Peluri(); 
    ben1.taytaTestiTiedoilla(); 
    assertEquals("From: Peluri line: 114", "Ben_P", ben1.getPNimi());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTTila126 */
  @Test
  public void testGetTTila126() {    // Peluri: 126
    Peluri ben1 = new Peluri(); 
    ben1.taytaTestiTiedoilla(); 
    assertEquals("From: Peluri line: 129", 1000, ben1.getTTila()); 
  } // Generated by ComTest END
}