package Kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.24 16:09:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeluriTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi56 */
  @Test
  public void testRekisteroi56() {    // Peluri: 56
    Peluri ben1 = new Peluri(); 
    assertEquals("From: Peluri line: 58", 0, ben1.getPeluriId()); 
    ben1.rekisteroi(); 
    Peluri ben2 = new Peluri(); 
    ben2.rekisteroi(); 
    int n1 = ben1.getPeluriId(); 
    int n2 = ben2.getPeluriId(); 
    assertEquals("From: Peluri line: 64", n2-1, n1); 
  } // Generated by ComTest END
}