package Kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.29 00:48:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeluritTest {



  // Generated by ComTest BEGIN
  /** testLisaa48 */
  @Test
  public void testLisaa48() {    // Pelurit: 48
    Pelurit pelurit = new Pelurit(); 
    Peluri ben1 = new Peluri(); 
    Peluri ben2 = new Peluri(); 
    assertEquals("From: Pelurit line: 52", 0, pelurit.getLkm()); 
    pelurit.lisaa(ben1); assertEquals("From: Pelurit line: 53", 1, pelurit.getLkm()); 
    pelurit.lisaa(ben2); assertEquals("From: Pelurit line: 54", 2, pelurit.getLkm()); 
    pelurit.lisaa(ben1); assertEquals("From: Pelurit line: 55", 3, pelurit.getLkm()); 
    assertEquals("From: Pelurit line: 56", ben1, pelurit.anna(0)); 
    assertEquals("From: Pelurit line: 57", ben2, pelurit.anna(1)); 
    assertEquals("From: Pelurit line: 58", ben1, pelurit.anna(2)); 
    assertEquals("From: Pelurit line: 59", false, pelurit.anna(1) == ben1); 
    assertEquals("From: Pelurit line: 60", true, pelurit.anna(1) == ben2); 
    try {
    assertEquals("From: Pelurit line: 61", ben1, pelurit.anna(3)); 
    fail("Pelurit: 61 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pelurit.lisaa(ben1); assertEquals("From: Pelurit line: 62", 4, pelurit.getLkm()); 
    pelurit.lisaa(ben1); assertEquals("From: Pelurit line: 63", 5, pelurit.getLkm()); 
    pelurit.lisaa(ben1); assertEquals("From: Pelurit line: 64", 6, pelurit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetLkm101 
   * @throws SailoException when error
   */
  @Test
  public void testGetLkm101() throws SailoException {    // Pelurit: 101
    Pelurit pelurit = new Pelurit(); 
    Peluri ben1 = new Peluri(); 
    Peluri ben2 = new Peluri(); 
    assertEquals("From: Pelurit line: 106", 0, pelurit.getLkm()); 
    pelurit.lisaa(ben1); assertEquals("From: Pelurit line: 107", 1, pelurit.getLkm()); 
    pelurit.lisaa(ben2); assertEquals("From: Pelurit line: 108", 2, pelurit.getLkm()); 
  } // Generated by ComTest END
}