package Kerho.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kerho.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.24 17:47:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeluritTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa34 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa34() throws SailoException {    // Pelurit: 34
    Pelurit pelurit = new Pelurit(); 
    Peluri ben1 = new Peluri(); 
    Peluri ben2 = new Peluri(); 
    assertEquals("From: Pelurit line: 39", 0, pelurit.getLkm()); 
    pelurit.lisaa(ben1); assertEquals("From: Pelurit line: 40", 1, pelurit.getLkm()); 
    pelurit.lisaa(ben2); assertEquals("From: Pelurit line: 41", 2, pelurit.getLkm()); 
    pelurit.lisaa(ben1); assertEquals("From: Pelurit line: 42", 3, pelurit.getLkm()); 
    assertEquals("From: Pelurit line: 43", ben1, pelurit.anna(0)); 
    assertEquals("From: Pelurit line: 44", ben2, pelurit.anna(1)); 
    assertEquals("From: Pelurit line: 45", ben1, pelurit.anna(2)); 
    assertEquals("From: Pelurit line: 46", false, pelurit.anna(1) == ben1); 
    assertEquals("From: Pelurit line: 47", true, pelurit.anna(1) == ben2); 
    try {
    assertEquals("From: Pelurit line: 48", ben1, pelurit.anna(3)); 
    fail("Pelurit: 48 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pelurit.lisaa(ben1); assertEquals("From: Pelurit line: 49", 4, pelurit.getLkm()); 
    pelurit.lisaa(ben1); assertEquals("From: Pelurit line: 50", 5, pelurit.getLkm()); 
    try {
    pelurit.lisaa(ben1); 
    fail("Pelurit: 51 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetLkm81 
   * @throws SailoException when error
   */
  @Test
  public void testGetLkm81() throws SailoException {    // Pelurit: 81
    Pelurit pelurit = new Pelurit(); 
    Peluri ben1 = new Peluri(); 
    Peluri ben2 = new Peluri(); 
    assertEquals("From: Pelurit line: 86", 0, pelurit.getLkm()); 
    pelurit.lisaa(ben1); assertEquals("From: Pelurit line: 87", 1, pelurit.getLkm()); 
    pelurit.lisaa(ben2); assertEquals("From: Pelurit line: 88", 2, pelurit.getLkm()); 
  } // Generated by ComTest END
}